name: Update Dependencies and Build Docker Image

on:
  schedule:
    - cron: '0 11 * * *'

jobs:
  update-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
        password: '${{ secrets.DOCKERHUB_TOKEN }}'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install poetry
      run: pipx install poetry==1.7.0

    - name: Update dependencies
      run: |
        poetry update
        poetry export -f requirements.txt --output requirements.txt --without-hashes

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          pysergio/hiroshi
        tags: |
          type=schedule,pattern=latest

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: 'linux/amd64,linux/arm64'
        push: true
        tags: '${{ steps.meta.outputs.tags }}'
        labels: '${{ steps.meta.outputs.labels }}'
        cache-from: 'type=registry,ref=pysergio/hiroshi:buildcache'
        cache-to: 'type=registry,ref=pysergio/hiroshi:buildcache,mode=max'

